### ISSUE TITLE
Add soname to libnss_tcb.so?

### ISSUE THREAD

**Issue by jas4711** [openwall/tcb#21]
The `libtcb.so` file is built with `-Wl,-soname` but `libnss_tcb.so` is not.  Is that intentional?  Debian's lintian complains about this library, and asks that it is built with a soname.  I don't know what the praxis is for NSS modules, but I'm also not sure it hurts.  Thoughts?  Could you add it?

**Comment by ldv-alt** [comment]
Sorry, I don't think we build `libnss_tcb.so`, did you mean `libnss_tcb.so.2`?

From one side, `libnss_tcb.so.2` behaves like a plugin rather than a regular shared library: it isn't linked with, it's being dlopen'ed instead, so technically speaking it doesn't need a soname.
From another side, adding a soname shouldn't cause any issues to anyone, so if it would make somebody happy, I don't mind adding it.

**Comment by jas4711** [comment]
Good point.  I suggest to close this as `wontfix` since it looks like a lintian false positive, unless someone can provide better justification for adding the soname.  I've seen that others disable the complaint like this, and I will do something similar.

https://salsa.debian.org/glibc-team/libnss-nis/-/blob/master/debian/lintian-overrides

**Comment by besser82** [comment]
@ldv-alt, @jas4711, this has already been addressed in https://github.com/openwall/tcb/commit/31680980473a41fc7feeae30739549849ac379fb.

**Comment by solardiz** [comment]
@besser82 Oh, thanks! I see that this commit is later than tcb-1.2, so perhaps @jas4711 was only testing the release?

**Comment by jas4711** [comment]
Thanks - yes, indeed, I was looking at v1.2 -- so this begs another question: could you make a new release? :)

**Comment by solardiz** [comment]
We definitely ought to make a new release, but on one hand it feels reasonable to fully process @besser82's pending PR and on the other they're not trivial enough for us to do so confidently while we're not currently focusing on the project, so this gets postponed. :-(
